/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BottomSheetSnapPoint, NBottomSheetClosingStartedDetail } from "./components/bottom-sheet/types";
import { ButtonColor, ButtonSize, ButtonVariant, NativeButtonType } from "./components/button/_shared/button.types";
import { ButtonToggleColor, ButtonToggleRounded, ButtonToggleSize } from "./components/button/n-button-toggle-group/type";
import { CheapColor, CheapSize, CheapVariant } from "./components/cheap/type";
import { ComponentType, DialogPlacement } from "./components/dialog/types";
import { ComponentType as ComponentType1 } from "./components/dialog/n-dynamic-component";
import { InputType, Size } from "./components/input/type";
import { LabelPosition } from "./components/switch/type";
import { ColumnPadding, ColumnType, NTableColumnConfigAlign, SortBy, SortOrder } from "./components/table/types";
import { TextTag, TextVariant } from "./components/typography/text/n-text";
import { Position, Toast, Variants } from "./components/toast/types";
export { BottomSheetSnapPoint, NBottomSheetClosingStartedDetail } from "./components/bottom-sheet/types";
export { ButtonColor, ButtonSize, ButtonVariant, NativeButtonType } from "./components/button/_shared/button.types";
export { ButtonToggleColor, ButtonToggleRounded, ButtonToggleSize } from "./components/button/n-button-toggle-group/type";
export { CheapColor, CheapSize, CheapVariant } from "./components/cheap/type";
export { ComponentType, DialogPlacement } from "./components/dialog/types";
export { ComponentType as ComponentType1 } from "./components/dialog/n-dynamic-component";
export { InputType, Size } from "./components/input/type";
export { LabelPosition } from "./components/switch/type";
export { ColumnPadding, ColumnType, NTableColumnConfigAlign, SortBy, SortOrder } from "./components/table/types";
export { TextTag, TextVariant } from "./components/typography/text/n-text";
export { Position, Toast, Variants } from "./components/toast/types";
export namespace Components {
    interface NAccordion {
        /**
          * @default 'false'
         */
        "accordionActive": string;
        /**
          * @default ''
         */
        "accordionGroupId": string;
        /**
          * @default -1
         */
        "accordionIndex": number;
        /**
          * @default ''
         */
        "accordionTitle": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "elevation": boolean;
        /**
          * @default false
         */
        "hasDivider": boolean;
    }
    interface NAccordionGroup {
        /**
          * @default 0
         */
        "modelValue": number | number[];
    }
    interface NBottomSheet {
        "afterClose"?: () => void;
        "afterOpen"?: () => void;
        /**
          * @default true
         */
        "blocking": boolean;
        /**
          * @default true
         */
        "canBackdropClose": boolean;
        /**
          * @default true
         */
        "canSwipeClose": boolean;
        /**
          * @default true
         */
        "closable": boolean;
        "close": () => Promise<void>;
        "contentClass"?: string;
        /**
          * @default 300
         */
        "duration": number;
        /**
          * @default false
         */
        "expandable": boolean;
        "footerClass"?: string;
        /**
          * @default true
         */
        "hashBased": boolean;
        "headerClass"?: string;
        "height"?: number;
        "initialSnapPoint"?: number;
        /**
          * @default false
         */
        "modelValue": boolean;
        "open": () => Promise<void>;
        /**
          * @default false
         */
        "removeFooterPadding": boolean;
        "snapPoints"?: BottomSheetSnapPoint[];
    }
    interface NBox {
        /**
          * @default 'none'
         */
        "elevation"?: 'none' | 'small' | 'medium' | 'large';
    }
    interface NButton {
        /**
          * @default BUTTON_COLOR.GREEN
         */
        "color": ButtonColor;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default BUTTON_SIZE.MIDDLE
         */
        "size": ButtonSize;
        /**
          * @default BUTTON_NATIVE_TYPE.BUTTON
         */
        "type": NativeButtonType;
        /**
          * @default BUTTON_VARIANT.FILL
         */
        "variant": ButtonVariant;
    }
    interface NButtonIcon {
        /**
          * @default BUTTON_COLOR.GREEN
         */
        "color": ButtonColor;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default BUTTON_SIZE.MIDDLE
         */
        "size": ButtonSize;
        /**
          * @default BUTTON_NATIVE_TYPE.BUTTON
         */
        "type": NativeButtonType;
        /**
          * @default BUTTON_VARIANT.FILL
         */
        "variant": ButtonVariant;
    }
    interface NButtonToggle {
        /**
          * @default false
         */
        "active": boolean;
        /**
          * @default ''
         */
        "badge": string;
        /**
          * @default BUTTON_COLOR.GREEN
         */
        "color": ButtonToggleColor;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default -1
         */
        "focusTabIndex": number;
        /**
          * @default 0
         */
        "index": number;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default BUTTON_TOGGLE_ROUNDED.FULL
         */
        "rounded": ButtonToggleRounded;
        /**
          * @default BUTTON_SIZE.SMALL
         */
        "size": ButtonToggleSize;
    }
    interface NButtonToggleGroup {
        /**
          * @default BUTTON_COLOR.GREEN
         */
        "color": ButtonToggleColor;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 0
         */
        "modelValue": number;
        /**
          * @default BUTTON_TOGGLE_ROUNDED.FULL
         */
        "rounded": ButtonToggleRounded;
        /**
          * @default BUTTON_SIZE.SMALL
         */
        "size": ButtonToggleSize;
    }
    interface NCheap {
        /**
          * @default true
         */
        "closable": boolean;
        /**
          * @default 'gray'
         */
        "color": CheapColor;
        /**
          * @default ''
         */
        "label": string | number;
        "modelValue"?: boolean;
        /**
          * @default false
         */
        "selectable": boolean;
        /**
          * @default false
         */
        "showIcon": boolean;
        /**
          * @default 'middle'
         */
        "size": CheapSize;
        /**
          * @default 'fill'
         */
        "variant": CheapVariant;
    }
    interface NDialog {
    }
    interface NDialogItem {
        "afterClose"?: () => void;
        "afterOpen"?: () => void;
        /**
          * @default ''
         */
        "bodyClass": string;
        "content": ComponentType | string;
        /**
          * @default false
         */
        "defaultExpanded": boolean;
        /**
          * @default 'rtl'
         */
        "dialogDirection": 'rtl' | 'ltr';
        "dialogId": string;
        "dialogTitle"?: ComponentType | string;
        /**
          * @default false
         */
        "expandable": boolean;
        "expandableLabel"?: ComponentType | string;
        "expandedContent"?: ComponentType | string;
        "footer"?: ComponentType | string;
        /**
          * @default ''
         */
        "footerClass": string;
        /**
          * @default false
         */
        "headerLess": boolean;
        "index": number;
        /**
          * @default false
         */
        "multiple": boolean;
        "placement"?: DialogPlacement;
        "referenceElementRef"?: HTMLElement | any;
        /**
          * @default ''
         */
        "wrapperClass": string;
        "zIndex": number;
    }
    interface NDrop {
    }
    interface NDynamicComponent {
        "class"?: string;
        "content": ComponentType1 | string;
    }
    interface NFade {
    }
    interface NField {
        /**
          * @default ''
         */
        "error": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'top'
         */
        "labelPosition": 'top' | 'inline';
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default true
         */
        "requiredSign": boolean;
        /**
          * @default true
         */
        "showError": boolean;
    }
    interface NInput {
        /**
          * @default true
         */
        "changeValueOnMouseWheel": boolean;
        /**
          * @default false
         */
        "clearable": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "error": string;
        /**
          * @default true
         */
        "forceEnDigit": boolean;
        /**
          * @default ''
         */
        "inputClass": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'top'
         */
        "labelPosition": 'top' | 'inline';
        /**
          * @default Infinity
         */
        "max": number;
        /**
          * @default -Infinity
         */
        "min": number;
        /**
          * @default ''
         */
        "modelValue": string | number;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default true
         */
        "requiredSign": boolean;
        /**
          * @default 3
         */
        "rows": number | string;
        /**
          * @default false
         */
        "showError": boolean;
        /**
          * @default 'middle'
         */
        "size": Size;
        /**
          * @default 1
         */
        "step": number;
        /**
          * @default 'text'
         */
        "type": InputType;
    }
    interface NLoading {
        /**
          * @default 10
         */
        "size": number;
    }
    interface NProgress {
        "backgroundColorCode": string;
        /**
          * @default 0
         */
        "percentage": number;
        /**
          * @default 'white'
         */
        "progressColorCode": string;
        /**
          * @default 10
         */
        "size": number;
    }
    interface NSwitch {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default LabelPosition.End
         */
        "labelPosition": LabelPosition;
        /**
          * @default false
         */
        "loading": boolean;
        "modelValue"?: boolean;
    }
    interface NTable {
        /**
          * @default ColumnPadding.Medium
         */
        "cellPadding": ColumnPadding;
        /**
          * @default []
         */
        "data": any[];
        /**
          * @default false
         */
        "fixedHeader": boolean;
        /**
          * @default 'id'
         */
        "identifier": string;
        /**
          * @default false
         */
        "selectable": boolean;
        /**
          * @default false
         */
        "sortMultiple": boolean;
        /**
          * @default true
         */
        "striped": boolean;
    }
    interface NTableColumn {
        /**
          * @default 'center'
         */
        "align": NTableColumnConfigAlign;
        "label"?: string;
        "prop"?: string;
        /**
          * @default false
         */
        "sortable": boolean;
        /**
          * @default ColumnType.Default
         */
        "type": ColumnType;
    }
    interface NTableHeader {
        /**
          * @default 'center'
         */
        "align": NTableColumnConfigAlign;
        "label": string;
        "prop": string;
        "sortIndex"?: number;
        /**
          * @default 'none'
         */
        "sortOrder": SortOrder;
        /**
          * @default false
         */
        "sortable": boolean;
    }
    interface NTableRow {
        /**
          * @default false
         */
        "highlighted": boolean;
        /**
          * @default 0
         */
        "index": number;
        /**
          * @default false
         */
        "isAllSelected": boolean;
        /**
          * @default false
         */
        "isClickable": boolean;
        "row": any;
        /**
          * @default true
         */
        "rowSplitter": boolean;
        /**
          * @default false
         */
        "selectable": boolean;
        /**
          * @default false
         */
        "showLoading": boolean;
        /**
          * @default false
         */
        "striped": boolean;
    }
    interface NText {
        /**
          * @default 'span'
         */
        "tag": TextTag;
        /**
          * @default 'body'
         */
        "variant": TextVariant;
        /**
          * @default 'regular'
         */
        "weight": 'regular' | 'medium' | 'bold';
    }
    interface NToast {
        "addToast": (toast: Toast) => Promise<void>;
        "clearAll": () => Promise<void>;
        /**
          * @default 0
         */
        "offset": number;
        /**
          * @default Position.Bottom
         */
        "position": Position;
        /**
          * @default false
         */
        "queued": boolean;
    }
    interface NToastItem {
        /**
          * @default true
         */
        "closable": boolean;
        "depth": number;
        /**
          * @default 3000
         */
        "duration": number;
        /**
          * @default true
         */
        "enabled": boolean;
        "index": number;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default ''
         */
        "message": string;
        /**
          * @default 0
         */
        "offset": number;
        /**
          * @default Position.Bottom
         */
        "position": Position;
        /**
          * @default false
         */
        "queued": boolean;
        /**
          * @default false
         */
        "removed": boolean;
        /**
          * @default false
         */
        "showIcon": boolean;
        "toastId": string;
        /**
          * @default Variants.Positive
         */
        "variant": Variants;
    }
}
export interface NAccordionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNAccordionElement;
}
export interface NAccordionGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNAccordionGroupElement;
}
export interface NBottomSheetCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNBottomSheetElement;
}
export interface NButtonToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNButtonToggleElement;
}
export interface NButtonToggleGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNButtonToggleGroupElement;
}
export interface NCheapCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNCheapElement;
}
export interface NDialogItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNDialogItemElement;
}
export interface NInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNInputElement;
}
export interface NSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNSwitchElement;
}
export interface NTableCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNTableElement;
}
export interface NTableHeaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNTableHeaderElement;
}
export interface NTableRowCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNTableRowElement;
}
export interface NToastItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLNToastItemElement;
}
declare global {
    interface HTMLNAccordionElementEventMap {
        "accordionToggleClick": number;
    }
    interface HTMLNAccordionElement extends Components.NAccordion, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNAccordionElementEventMap>(type: K, listener: (this: HTMLNAccordionElement, ev: NAccordionCustomEvent<HTMLNAccordionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNAccordionElementEventMap>(type: K, listener: (this: HTMLNAccordionElement, ev: NAccordionCustomEvent<HTMLNAccordionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNAccordionElement: {
        prototype: HTMLNAccordionElement;
        new (): HTMLNAccordionElement;
    };
    interface HTMLNAccordionGroupElementEventMap {
        "updateModelValue": number | number[];
    }
    interface HTMLNAccordionGroupElement extends Components.NAccordionGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNAccordionGroupElementEventMap>(type: K, listener: (this: HTMLNAccordionGroupElement, ev: NAccordionGroupCustomEvent<HTMLNAccordionGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNAccordionGroupElementEventMap>(type: K, listener: (this: HTMLNAccordionGroupElement, ev: NAccordionGroupCustomEvent<HTMLNAccordionGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNAccordionGroupElement: {
        prototype: HTMLNAccordionGroupElement;
        new (): HTMLNAccordionGroupElement;
    };
    interface HTMLNBottomSheetElementEventMap {
        "updateModelValue": boolean;
        "closing-started": NBottomSheetClosingStartedDetail;
        "instinct-height": number;
    }
    interface HTMLNBottomSheetElement extends Components.NBottomSheet, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNBottomSheetElementEventMap>(type: K, listener: (this: HTMLNBottomSheetElement, ev: NBottomSheetCustomEvent<HTMLNBottomSheetElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNBottomSheetElementEventMap>(type: K, listener: (this: HTMLNBottomSheetElement, ev: NBottomSheetCustomEvent<HTMLNBottomSheetElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNBottomSheetElement: {
        prototype: HTMLNBottomSheetElement;
        new (): HTMLNBottomSheetElement;
    };
    interface HTMLNBoxElement extends Components.NBox, HTMLStencilElement {
    }
    var HTMLNBoxElement: {
        prototype: HTMLNBoxElement;
        new (): HTMLNBoxElement;
    };
    interface HTMLNButtonElement extends Components.NButton, HTMLStencilElement {
    }
    var HTMLNButtonElement: {
        prototype: HTMLNButtonElement;
        new (): HTMLNButtonElement;
    };
    interface HTMLNButtonIconElement extends Components.NButtonIcon, HTMLStencilElement {
    }
    var HTMLNButtonIconElement: {
        prototype: HTMLNButtonIconElement;
        new (): HTMLNButtonIconElement;
    };
    interface HTMLNButtonToggleElementEventMap {
        "toggleSelect": number;
    }
    interface HTMLNButtonToggleElement extends Components.NButtonToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNButtonToggleElementEventMap>(type: K, listener: (this: HTMLNButtonToggleElement, ev: NButtonToggleCustomEvent<HTMLNButtonToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNButtonToggleElementEventMap>(type: K, listener: (this: HTMLNButtonToggleElement, ev: NButtonToggleCustomEvent<HTMLNButtonToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNButtonToggleElement: {
        prototype: HTMLNButtonToggleElement;
        new (): HTMLNButtonToggleElement;
    };
    interface HTMLNButtonToggleGroupElementEventMap {
        "modelValueChange": number;
    }
    interface HTMLNButtonToggleGroupElement extends Components.NButtonToggleGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNButtonToggleGroupElementEventMap>(type: K, listener: (this: HTMLNButtonToggleGroupElement, ev: NButtonToggleGroupCustomEvent<HTMLNButtonToggleGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNButtonToggleGroupElementEventMap>(type: K, listener: (this: HTMLNButtonToggleGroupElement, ev: NButtonToggleGroupCustomEvent<HTMLNButtonToggleGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNButtonToggleGroupElement: {
        prototype: HTMLNButtonToggleGroupElement;
        new (): HTMLNButtonToggleGroupElement;
    };
    interface HTMLNCheapElementEventMap {
        "close": void;
        "updateModelValue": boolean;
    }
    interface HTMLNCheapElement extends Components.NCheap, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNCheapElementEventMap>(type: K, listener: (this: HTMLNCheapElement, ev: NCheapCustomEvent<HTMLNCheapElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNCheapElementEventMap>(type: K, listener: (this: HTMLNCheapElement, ev: NCheapCustomEvent<HTMLNCheapElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNCheapElement: {
        prototype: HTMLNCheapElement;
        new (): HTMLNCheapElement;
    };
    interface HTMLNDialogElement extends Components.NDialog, HTMLStencilElement {
    }
    var HTMLNDialogElement: {
        prototype: HTMLNDialogElement;
        new (): HTMLNDialogElement;
    };
    interface HTMLNDialogItemElementEventMap {
        "afterCloseEvent": void;
        "afterOpenEvent": void;
        "updateExpanded": boolean;
        "positionError": { dialogId: string; error: unknown };
    }
    interface HTMLNDialogItemElement extends Components.NDialogItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNDialogItemElementEventMap>(type: K, listener: (this: HTMLNDialogItemElement, ev: NDialogItemCustomEvent<HTMLNDialogItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNDialogItemElementEventMap>(type: K, listener: (this: HTMLNDialogItemElement, ev: NDialogItemCustomEvent<HTMLNDialogItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNDialogItemElement: {
        prototype: HTMLNDialogItemElement;
        new (): HTMLNDialogItemElement;
    };
    interface HTMLNDropElement extends Components.NDrop, HTMLStencilElement {
    }
    var HTMLNDropElement: {
        prototype: HTMLNDropElement;
        new (): HTMLNDropElement;
    };
    interface HTMLNDynamicComponentElement extends Components.NDynamicComponent, HTMLStencilElement {
    }
    var HTMLNDynamicComponentElement: {
        prototype: HTMLNDynamicComponentElement;
        new (): HTMLNDynamicComponentElement;
    };
    interface HTMLNFadeElement extends Components.NFade, HTMLStencilElement {
    }
    var HTMLNFadeElement: {
        prototype: HTMLNFadeElement;
        new (): HTMLNFadeElement;
    };
    interface HTMLNFieldElement extends Components.NField, HTMLStencilElement {
    }
    var HTMLNFieldElement: {
        prototype: HTMLNFieldElement;
        new (): HTMLNFieldElement;
    };
    interface HTMLNInputElementEventMap {
        "updateModelValue": string | number;
    }
    interface HTMLNInputElement extends Components.NInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNInputElementEventMap>(type: K, listener: (this: HTMLNInputElement, ev: NInputCustomEvent<HTMLNInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNInputElementEventMap>(type: K, listener: (this: HTMLNInputElement, ev: NInputCustomEvent<HTMLNInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNInputElement: {
        prototype: HTMLNInputElement;
        new (): HTMLNInputElement;
    };
    interface HTMLNLoadingElement extends Components.NLoading, HTMLStencilElement {
    }
    var HTMLNLoadingElement: {
        prototype: HTMLNLoadingElement;
        new (): HTMLNLoadingElement;
    };
    interface HTMLNProgressElement extends Components.NProgress, HTMLStencilElement {
    }
    var HTMLNProgressElement: {
        prototype: HTMLNProgressElement;
        new (): HTMLNProgressElement;
    };
    interface HTMLNSwitchElementEventMap {
        "modelValueChange": boolean;
    }
    interface HTMLNSwitchElement extends Components.NSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNSwitchElementEventMap>(type: K, listener: (this: HTMLNSwitchElement, ev: NSwitchCustomEvent<HTMLNSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNSwitchElementEventMap>(type: K, listener: (this: HTMLNSwitchElement, ev: NSwitchCustomEvent<HTMLNSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNSwitchElement: {
        prototype: HTMLNSwitchElement;
        new (): HTMLNSwitchElement;
    };
    interface HTMLNTableElementEventMap {
        "selectedRowsChange": any[];
        "sortChange": SortBy[];
    }
    interface HTMLNTableElement extends Components.NTable, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNTableElementEventMap>(type: K, listener: (this: HTMLNTableElement, ev: NTableCustomEvent<HTMLNTableElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNTableElementEventMap>(type: K, listener: (this: HTMLNTableElement, ev: NTableCustomEvent<HTMLNTableElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNTableElement: {
        prototype: HTMLNTableElement;
        new (): HTMLNTableElement;
    };
    interface HTMLNTableColumnElement extends Components.NTableColumn, HTMLStencilElement {
    }
    var HTMLNTableColumnElement: {
        prototype: HTMLNTableColumnElement;
        new (): HTMLNTableColumnElement;
    };
    interface HTMLNTableHeaderElementEventMap {
        "sortChange": {
      prop: string;
      order: SortOrder;
    };
    }
    interface HTMLNTableHeaderElement extends Components.NTableHeader, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNTableHeaderElementEventMap>(type: K, listener: (this: HTMLNTableHeaderElement, ev: NTableHeaderCustomEvent<HTMLNTableHeaderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNTableHeaderElementEventMap>(type: K, listener: (this: HTMLNTableHeaderElement, ev: NTableHeaderCustomEvent<HTMLNTableHeaderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNTableHeaderElement: {
        prototype: HTMLNTableHeaderElement;
        new (): HTMLNTableHeaderElement;
    };
    interface HTMLNTableRowElementEventMap {
        "rowClick": any;
        "rowSelectionChange": any;
    }
    interface HTMLNTableRowElement extends Components.NTableRow, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNTableRowElementEventMap>(type: K, listener: (this: HTMLNTableRowElement, ev: NTableRowCustomEvent<HTMLNTableRowElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNTableRowElementEventMap>(type: K, listener: (this: HTMLNTableRowElement, ev: NTableRowCustomEvent<HTMLNTableRowElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNTableRowElement: {
        prototype: HTMLNTableRowElement;
        new (): HTMLNTableRowElement;
    };
    interface HTMLNTextElement extends Components.NText, HTMLStencilElement {
    }
    var HTMLNTextElement: {
        prototype: HTMLNTextElement;
        new (): HTMLNTextElement;
    };
    interface HTMLNToastElement extends Components.NToast, HTMLStencilElement {
    }
    var HTMLNToastElement: {
        prototype: HTMLNToastElement;
        new (): HTMLNToastElement;
    };
    interface HTMLNToastItemElementEventMap {
        "remove": string;
        "removeAll": void;
    }
    interface HTMLNToastItemElement extends Components.NToastItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLNToastItemElementEventMap>(type: K, listener: (this: HTMLNToastItemElement, ev: NToastItemCustomEvent<HTMLNToastItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLNToastItemElementEventMap>(type: K, listener: (this: HTMLNToastItemElement, ev: NToastItemCustomEvent<HTMLNToastItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLNToastItemElement: {
        prototype: HTMLNToastItemElement;
        new (): HTMLNToastItemElement;
    };
    interface HTMLElementTagNameMap {
        "n-accordion": HTMLNAccordionElement;
        "n-accordion-group": HTMLNAccordionGroupElement;
        "n-bottom-sheet": HTMLNBottomSheetElement;
        "n-box": HTMLNBoxElement;
        "n-button": HTMLNButtonElement;
        "n-button-icon": HTMLNButtonIconElement;
        "n-button-toggle": HTMLNButtonToggleElement;
        "n-button-toggle-group": HTMLNButtonToggleGroupElement;
        "n-cheap": HTMLNCheapElement;
        "n-dialog": HTMLNDialogElement;
        "n-dialog-item": HTMLNDialogItemElement;
        "n-drop": HTMLNDropElement;
        "n-dynamic-component": HTMLNDynamicComponentElement;
        "n-fade": HTMLNFadeElement;
        "n-field": HTMLNFieldElement;
        "n-input": HTMLNInputElement;
        "n-loading": HTMLNLoadingElement;
        "n-progress": HTMLNProgressElement;
        "n-switch": HTMLNSwitchElement;
        "n-table": HTMLNTableElement;
        "n-table-column": HTMLNTableColumnElement;
        "n-table-header": HTMLNTableHeaderElement;
        "n-table-row": HTMLNTableRowElement;
        "n-text": HTMLNTextElement;
        "n-toast": HTMLNToastElement;
        "n-toast-item": HTMLNToastItemElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface NAccordion {
        /**
          * @default 'false'
         */
        "accordionActive"?: string;
        /**
          * @default ''
         */
        "accordionGroupId"?: string;
        /**
          * @default -1
         */
        "accordionIndex"?: number;
        /**
          * @default ''
         */
        "accordionTitle"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "elevation"?: boolean;
        /**
          * @default false
         */
        "hasDivider"?: boolean;
        "onAccordionToggleClick"?: (event: NAccordionCustomEvent<number>) => void;
    }
    interface NAccordionGroup {
        /**
          * @default 0
         */
        "modelValue"?: number | number[];
        "onUpdateModelValue"?: (event: NAccordionGroupCustomEvent<number | number[]>) => void;
    }
    interface NBottomSheet {
        "afterClose"?: () => void;
        "afterOpen"?: () => void;
        /**
          * @default true
         */
        "blocking"?: boolean;
        /**
          * @default true
         */
        "canBackdropClose"?: boolean;
        /**
          * @default true
         */
        "canSwipeClose"?: boolean;
        /**
          * @default true
         */
        "closable"?: boolean;
        "contentClass"?: string;
        /**
          * @default 300
         */
        "duration"?: number;
        /**
          * @default false
         */
        "expandable"?: boolean;
        "footerClass"?: string;
        /**
          * @default true
         */
        "hashBased"?: boolean;
        "headerClass"?: string;
        "height"?: number;
        "initialSnapPoint"?: number;
        /**
          * @default false
         */
        "modelValue"?: boolean;
        "onClosing-started"?: (event: NBottomSheetCustomEvent<NBottomSheetClosingStartedDetail>) => void;
        "onInstinct-height"?: (event: NBottomSheetCustomEvent<number>) => void;
        "onUpdateModelValue"?: (event: NBottomSheetCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "removeFooterPadding"?: boolean;
        "snapPoints"?: BottomSheetSnapPoint[];
    }
    interface NBox {
        /**
          * @default 'none'
         */
        "elevation"?: 'none' | 'small' | 'medium' | 'large';
    }
    interface NButton {
        /**
          * @default BUTTON_COLOR.GREEN
         */
        "color"?: ButtonColor;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default BUTTON_SIZE.MIDDLE
         */
        "size"?: ButtonSize;
        /**
          * @default BUTTON_NATIVE_TYPE.BUTTON
         */
        "type"?: NativeButtonType;
        /**
          * @default BUTTON_VARIANT.FILL
         */
        "variant"?: ButtonVariant;
    }
    interface NButtonIcon {
        /**
          * @default BUTTON_COLOR.GREEN
         */
        "color"?: ButtonColor;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default BUTTON_SIZE.MIDDLE
         */
        "size"?: ButtonSize;
        /**
          * @default BUTTON_NATIVE_TYPE.BUTTON
         */
        "type"?: NativeButtonType;
        /**
          * @default BUTTON_VARIANT.FILL
         */
        "variant"?: ButtonVariant;
    }
    interface NButtonToggle {
        /**
          * @default false
         */
        "active"?: boolean;
        /**
          * @default ''
         */
        "badge"?: string;
        /**
          * @default BUTTON_COLOR.GREEN
         */
        "color"?: ButtonToggleColor;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default -1
         */
        "focusTabIndex"?: number;
        /**
          * @default 0
         */
        "index"?: number;
        /**
          * @default ''
         */
        "label"?: string;
        "onToggleSelect"?: (event: NButtonToggleCustomEvent<number>) => void;
        /**
          * @default BUTTON_TOGGLE_ROUNDED.FULL
         */
        "rounded"?: ButtonToggleRounded;
        /**
          * @default BUTTON_SIZE.SMALL
         */
        "size"?: ButtonToggleSize;
    }
    interface NButtonToggleGroup {
        /**
          * @default BUTTON_COLOR.GREEN
         */
        "color"?: ButtonToggleColor;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 0
         */
        "modelValue"?: number;
        "onModelValueChange"?: (event: NButtonToggleGroupCustomEvent<number>) => void;
        /**
          * @default BUTTON_TOGGLE_ROUNDED.FULL
         */
        "rounded"?: ButtonToggleRounded;
        /**
          * @default BUTTON_SIZE.SMALL
         */
        "size"?: ButtonToggleSize;
    }
    interface NCheap {
        /**
          * @default true
         */
        "closable"?: boolean;
        /**
          * @default 'gray'
         */
        "color"?: CheapColor;
        /**
          * @default ''
         */
        "label"?: string | number;
        "modelValue"?: boolean;
        "onClose"?: (event: NCheapCustomEvent<void>) => void;
        "onUpdateModelValue"?: (event: NCheapCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "selectable"?: boolean;
        /**
          * @default false
         */
        "showIcon"?: boolean;
        /**
          * @default 'middle'
         */
        "size"?: CheapSize;
        /**
          * @default 'fill'
         */
        "variant"?: CheapVariant;
    }
    interface NDialog {
    }
    interface NDialogItem {
        "afterClose"?: () => void;
        "afterOpen"?: () => void;
        /**
          * @default ''
         */
        "bodyClass"?: string;
        "content": ComponentType | string;
        /**
          * @default false
         */
        "defaultExpanded"?: boolean;
        /**
          * @default 'rtl'
         */
        "dialogDirection"?: 'rtl' | 'ltr';
        "dialogId": string;
        "dialogTitle"?: ComponentType | string;
        /**
          * @default false
         */
        "expandable"?: boolean;
        "expandableLabel"?: ComponentType | string;
        "expandedContent"?: ComponentType | string;
        "footer"?: ComponentType | string;
        /**
          * @default ''
         */
        "footerClass"?: string;
        /**
          * @default false
         */
        "headerLess"?: boolean;
        "index": number;
        /**
          * @default false
         */
        "multiple"?: boolean;
        "onAfterCloseEvent"?: (event: NDialogItemCustomEvent<void>) => void;
        "onAfterOpenEvent"?: (event: NDialogItemCustomEvent<void>) => void;
        "onPositionError"?: (event: NDialogItemCustomEvent<{ dialogId: string; error: unknown }>) => void;
        "onUpdateExpanded"?: (event: NDialogItemCustomEvent<boolean>) => void;
        "placement"?: DialogPlacement;
        "referenceElementRef"?: HTMLElement | any;
        /**
          * @default ''
         */
        "wrapperClass"?: string;
        "zIndex": number;
    }
    interface NDrop {
    }
    interface NDynamicComponent {
        "class"?: string;
        "content": ComponentType1 | string;
    }
    interface NFade {
    }
    interface NField {
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default 'top'
         */
        "labelPosition"?: 'top' | 'inline';
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default true
         */
        "requiredSign"?: boolean;
        /**
          * @default true
         */
        "showError"?: boolean;
    }
    interface NInput {
        /**
          * @default true
         */
        "changeValueOnMouseWheel"?: boolean;
        /**
          * @default false
         */
        "clearable"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "error"?: string;
        /**
          * @default true
         */
        "forceEnDigit"?: boolean;
        /**
          * @default ''
         */
        "inputClass"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default 'top'
         */
        "labelPosition"?: 'top' | 'inline';
        /**
          * @default Infinity
         */
        "max"?: number;
        /**
          * @default -Infinity
         */
        "min"?: number;
        /**
          * @default ''
         */
        "modelValue"?: string | number;
        "onUpdateModelValue"?: (event: NInputCustomEvent<string | number>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default true
         */
        "requiredSign"?: boolean;
        /**
          * @default 3
         */
        "rows"?: number | string;
        /**
          * @default false
         */
        "showError"?: boolean;
        /**
          * @default 'middle'
         */
        "size"?: Size;
        /**
          * @default 1
         */
        "step"?: number;
        /**
          * @default 'text'
         */
        "type"?: InputType;
    }
    interface NLoading {
        /**
          * @default 10
         */
        "size"?: number;
    }
    interface NProgress {
        "backgroundColorCode": string;
        /**
          * @default 0
         */
        "percentage"?: number;
        /**
          * @default 'white'
         */
        "progressColorCode"?: string;
        /**
          * @default 10
         */
        "size"?: number;
    }
    interface NSwitch {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default LabelPosition.End
         */
        "labelPosition"?: LabelPosition;
        /**
          * @default false
         */
        "loading"?: boolean;
        "modelValue"?: boolean;
        "onModelValueChange"?: (event: NSwitchCustomEvent<boolean>) => void;
    }
    interface NTable {
        /**
          * @default ColumnPadding.Medium
         */
        "cellPadding"?: ColumnPadding;
        /**
          * @default []
         */
        "data"?: any[];
        /**
          * @default false
         */
        "fixedHeader"?: boolean;
        /**
          * @default 'id'
         */
        "identifier"?: string;
        "onSelectedRowsChange"?: (event: NTableCustomEvent<any[]>) => void;
        "onSortChange"?: (event: NTableCustomEvent<SortBy[]>) => void;
        /**
          * @default false
         */
        "selectable"?: boolean;
        /**
          * @default false
         */
        "sortMultiple"?: boolean;
        /**
          * @default true
         */
        "striped"?: boolean;
    }
    interface NTableColumn {
        /**
          * @default 'center'
         */
        "align"?: NTableColumnConfigAlign;
        "label"?: string;
        "prop"?: string;
        /**
          * @default false
         */
        "sortable"?: boolean;
        /**
          * @default ColumnType.Default
         */
        "type"?: ColumnType;
    }
    interface NTableHeader {
        /**
          * @default 'center'
         */
        "align"?: NTableColumnConfigAlign;
        "label": string;
        "onSortChange"?: (event: NTableHeaderCustomEvent<{
      prop: string;
      order: SortOrder;
    }>) => void;
        "prop": string;
        "sortIndex"?: number;
        /**
          * @default 'none'
         */
        "sortOrder"?: SortOrder;
        /**
          * @default false
         */
        "sortable"?: boolean;
    }
    interface NTableRow {
        /**
          * @default false
         */
        "highlighted"?: boolean;
        /**
          * @default 0
         */
        "index"?: number;
        /**
          * @default false
         */
        "isAllSelected"?: boolean;
        /**
          * @default false
         */
        "isClickable"?: boolean;
        "onRowClick"?: (event: NTableRowCustomEvent<any>) => void;
        "onRowSelectionChange"?: (event: NTableRowCustomEvent<any>) => void;
        "row"?: any;
        /**
          * @default true
         */
        "rowSplitter"?: boolean;
        /**
          * @default false
         */
        "selectable"?: boolean;
        /**
          * @default false
         */
        "showLoading"?: boolean;
        /**
          * @default false
         */
        "striped"?: boolean;
    }
    interface NText {
        /**
          * @default 'span'
         */
        "tag"?: TextTag;
        /**
          * @default 'body'
         */
        "variant"?: TextVariant;
        /**
          * @default 'regular'
         */
        "weight"?: 'regular' | 'medium' | 'bold';
    }
    interface NToast {
        /**
          * @default 0
         */
        "offset"?: number;
        /**
          * @default Position.Bottom
         */
        "position"?: Position;
        /**
          * @default false
         */
        "queued"?: boolean;
    }
    interface NToastItem {
        /**
          * @default true
         */
        "closable"?: boolean;
        "depth": number;
        /**
          * @default 3000
         */
        "duration"?: number;
        /**
          * @default true
         */
        "enabled"?: boolean;
        "index": number;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default ''
         */
        "message"?: string;
        /**
          * @default 0
         */
        "offset"?: number;
        "onRemove"?: (event: NToastItemCustomEvent<string>) => void;
        "onRemoveAll"?: (event: NToastItemCustomEvent<void>) => void;
        /**
          * @default Position.Bottom
         */
        "position"?: Position;
        /**
          * @default false
         */
        "queued"?: boolean;
        /**
          * @default false
         */
        "removed"?: boolean;
        /**
          * @default false
         */
        "showIcon"?: boolean;
        "toastId": string;
        /**
          * @default Variants.Positive
         */
        "variant"?: Variants;
    }

    interface NAccordionAttributes {
        "accordionTitle": string;
        "disabled": boolean;
        "hasDivider": boolean;
        "elevation": boolean;
        "accordionIndex": number;
        "accordionActive": string;
        "accordionGroupId": string;
    }
    interface NAccordionGroupAttributes {
        "modelValue": number | number[];
    }
    interface NBottomSheetAttributes {
        "modelValue": boolean;
        "duration": number;
        "blocking": boolean;
        "expandable": boolean;
        "closable": boolean;
        "canSwipeClose": boolean;
        "canBackdropClose": boolean;
        "hashBased": boolean;
        "height": number;
        "initialSnapPoint": number;
        "headerClass": string;
        "contentClass": string;
        "footerClass": string;
        "removeFooterPadding": boolean;
    }
    interface NBoxAttributes {
        "elevation": 'none' | 'small' | 'medium' | 'large';
    }
    interface NButtonAttributes {
        "size": ButtonSize;
        "variant": ButtonVariant;
        "color": ButtonColor;
        "loading": boolean;
        "disabled": boolean;
        "type": NativeButtonType;
    }
    interface NButtonIconAttributes {
        "size": ButtonSize;
        "variant": ButtonVariant;
        "color": ButtonColor;
        "loading": boolean;
        "disabled": boolean;
        "type": NativeButtonType;
    }
    interface NButtonToggleAttributes {
        "index": number;
        "active": boolean;
        "label": string;
        "badge": string;
        "color": ButtonToggleColor;
        "size": ButtonToggleSize;
        "rounded": ButtonToggleRounded;
        "disabled": boolean;
        "focusTabIndex": number;
    }
    interface NButtonToggleGroupAttributes {
        "modelValue": number;
        "disabled": boolean;
        "color": ButtonToggleColor;
        "size": ButtonToggleSize;
        "rounded": ButtonToggleRounded;
    }
    interface NCheapAttributes {
        "modelValue": boolean;
        "variant": CheapVariant;
        "closable": boolean;
        "showIcon": boolean;
        "label": string;
        "size": CheapSize;
        "color": CheapColor;
        "selectable": boolean;
    }
    interface NDialogItemAttributes {
        "dialogId": string;
        "zIndex": number;
        "index": number;
        "dialogDirection": 'rtl' | 'ltr';
        "content": ComponentType | string;
        "dialogTitle": ComponentType | string;
        "expandableLabel": ComponentType | string;
        "expandable": boolean;
        "defaultExpanded": boolean;
        "expandedContent": ComponentType | string;
        "footer": ComponentType | string;
        "bodyClass": string;
        "wrapperClass": string;
        "footerClass": string;
        "multiple": boolean;
        "referenceElementRef": string;
        "placement": DialogPlacement;
        "headerLess": boolean;
    }
    interface NDynamicComponentAttributes {
        "content": ComponentType | string;
        "class": string;
    }
    interface NFieldAttributes {
        "showError": boolean;
        "error": string;
        "label": string;
        "labelPosition": 'top' | 'inline';
        "required": boolean;
        "requiredSign": boolean;
    }
    interface NInputAttributes {
        "modelValue": string;
        "disabled": boolean;
        "type": InputType;
        "label": string;
        "labelPosition": 'top' | 'inline';
        "placeholder": string;
        "showError": boolean;
        "error": string;
        "required": boolean;
        "requiredSign": boolean;
        "clearable": boolean;
        "rows": string;
        "inputClass": string;
        "forceEnDigit": boolean;
        "size": Size;
        "min": number;
        "max": number;
        "step": number;
        "changeValueOnMouseWheel": boolean;
    }
    interface NLoadingAttributes {
        "size": number;
    }
    interface NProgressAttributes {
        "percentage": number;
        "backgroundColorCode": string;
        "progressColorCode": string;
        "size": number;
    }
    interface NSwitchAttributes {
        "modelValue": boolean;
        "disabled": boolean;
        "loading": boolean;
        "label": string;
        "labelPosition": LabelPosition;
    }
    interface NTableAttributes {
        "striped": boolean;
        "selectable": boolean;
        "fixedHeader": boolean;
        "sortMultiple": boolean;
        "identifier": string;
        "cellPadding": ColumnPadding;
    }
    interface NTableColumnAttributes {
        "prop": string;
        "label": string;
        "type": ColumnType;
        "sortable": boolean;
        "align": NTableColumnConfigAlign;
    }
    interface NTableHeaderAttributes {
        "prop": string;
        "label": string;
        "sortable": boolean;
        "align": NTableColumnConfigAlign;
        "sortOrder": SortOrder;
        "sortIndex": number;
    }
    interface NTableRowAttributes {
        "row": string;
        "index": number;
        "highlighted": boolean;
        "striped": boolean;
        "rowSplitter": boolean;
        "showLoading": boolean;
        "selectable": boolean;
        "isAllSelected": boolean;
        "isClickable": boolean;
    }
    interface NTextAttributes {
        "variant": TextVariant;
        "tag": TextTag;
        "weight": 'regular' | 'medium' | 'bold';
    }
    interface NToastAttributes {
        "offset": number;
        "queued": boolean;
        "position": Position;
    }
    interface NToastItemAttributes {
        "toastId": string;
        "message": string;
        "duration": number;
        "variant": Variants;
        "loading": boolean;
        "closable": boolean;
        "showIcon": boolean;
        "index": number;
        "depth": number;
        "queued": boolean;
        "enabled": boolean;
        "position": Position;
        "offset": number;
        "removed": boolean;
    }

    interface IntrinsicElements {
        "n-accordion": Omit<NAccordion, keyof NAccordionAttributes> & { [K in keyof NAccordion & keyof NAccordionAttributes]?: NAccordion[K] } & { [K in keyof NAccordion & keyof NAccordionAttributes as `attr:${K}`]?: NAccordionAttributes[K] } & { [K in keyof NAccordion & keyof NAccordionAttributes as `prop:${K}`]?: NAccordion[K] };
        "n-accordion-group": Omit<NAccordionGroup, keyof NAccordionGroupAttributes> & { [K in keyof NAccordionGroup & keyof NAccordionGroupAttributes]?: NAccordionGroup[K] } & { [K in keyof NAccordionGroup & keyof NAccordionGroupAttributes as `attr:${K}`]?: NAccordionGroupAttributes[K] } & { [K in keyof NAccordionGroup & keyof NAccordionGroupAttributes as `prop:${K}`]?: NAccordionGroup[K] };
        "n-bottom-sheet": Omit<NBottomSheet, keyof NBottomSheetAttributes> & { [K in keyof NBottomSheet & keyof NBottomSheetAttributes]?: NBottomSheet[K] } & { [K in keyof NBottomSheet & keyof NBottomSheetAttributes as `attr:${K}`]?: NBottomSheetAttributes[K] } & { [K in keyof NBottomSheet & keyof NBottomSheetAttributes as `prop:${K}`]?: NBottomSheet[K] };
        "n-box": Omit<NBox, keyof NBoxAttributes> & { [K in keyof NBox & keyof NBoxAttributes]?: NBox[K] } & { [K in keyof NBox & keyof NBoxAttributes as `attr:${K}`]?: NBoxAttributes[K] } & { [K in keyof NBox & keyof NBoxAttributes as `prop:${K}`]?: NBox[K] };
        "n-button": Omit<NButton, keyof NButtonAttributes> & { [K in keyof NButton & keyof NButtonAttributes]?: NButton[K] } & { [K in keyof NButton & keyof NButtonAttributes as `attr:${K}`]?: NButtonAttributes[K] } & { [K in keyof NButton & keyof NButtonAttributes as `prop:${K}`]?: NButton[K] };
        "n-button-icon": Omit<NButtonIcon, keyof NButtonIconAttributes> & { [K in keyof NButtonIcon & keyof NButtonIconAttributes]?: NButtonIcon[K] } & { [K in keyof NButtonIcon & keyof NButtonIconAttributes as `attr:${K}`]?: NButtonIconAttributes[K] } & { [K in keyof NButtonIcon & keyof NButtonIconAttributes as `prop:${K}`]?: NButtonIcon[K] };
        "n-button-toggle": Omit<NButtonToggle, keyof NButtonToggleAttributes> & { [K in keyof NButtonToggle & keyof NButtonToggleAttributes]?: NButtonToggle[K] } & { [K in keyof NButtonToggle & keyof NButtonToggleAttributes as `attr:${K}`]?: NButtonToggleAttributes[K] } & { [K in keyof NButtonToggle & keyof NButtonToggleAttributes as `prop:${K}`]?: NButtonToggle[K] };
        "n-button-toggle-group": Omit<NButtonToggleGroup, keyof NButtonToggleGroupAttributes> & { [K in keyof NButtonToggleGroup & keyof NButtonToggleGroupAttributes]?: NButtonToggleGroup[K] } & { [K in keyof NButtonToggleGroup & keyof NButtonToggleGroupAttributes as `attr:${K}`]?: NButtonToggleGroupAttributes[K] } & { [K in keyof NButtonToggleGroup & keyof NButtonToggleGroupAttributes as `prop:${K}`]?: NButtonToggleGroup[K] };
        "n-cheap": Omit<NCheap, keyof NCheapAttributes> & { [K in keyof NCheap & keyof NCheapAttributes]?: NCheap[K] } & { [K in keyof NCheap & keyof NCheapAttributes as `attr:${K}`]?: NCheapAttributes[K] } & { [K in keyof NCheap & keyof NCheapAttributes as `prop:${K}`]?: NCheap[K] };
        "n-dialog": NDialog;
        "n-dialog-item": Omit<NDialogItem, keyof NDialogItemAttributes> & { [K in keyof NDialogItem & keyof NDialogItemAttributes]?: NDialogItem[K] } & { [K in keyof NDialogItem & keyof NDialogItemAttributes as `attr:${K}`]?: NDialogItemAttributes[K] } & { [K in keyof NDialogItem & keyof NDialogItemAttributes as `prop:${K}`]?: NDialogItem[K] } & OneOf<"dialogId", NDialogItem["dialogId"], NDialogItemAttributes["dialogId"]> & OneOf<"zIndex", NDialogItem["zIndex"], NDialogItemAttributes["zIndex"]> & OneOf<"index", NDialogItem["index"], NDialogItemAttributes["index"]> & OneOf<"content", NDialogItem["content"], NDialogItemAttributes["content"]>;
        "n-drop": NDrop;
        "n-dynamic-component": Omit<NDynamicComponent, keyof NDynamicComponentAttributes> & { [K in keyof NDynamicComponent & keyof NDynamicComponentAttributes]?: NDynamicComponent[K] } & { [K in keyof NDynamicComponent & keyof NDynamicComponentAttributes as `attr:${K}`]?: NDynamicComponentAttributes[K] } & { [K in keyof NDynamicComponent & keyof NDynamicComponentAttributes as `prop:${K}`]?: NDynamicComponent[K] } & OneOf<"content", NDynamicComponent["content"], NDynamicComponentAttributes["content"]>;
        "n-fade": NFade;
        "n-field": Omit<NField, keyof NFieldAttributes> & { [K in keyof NField & keyof NFieldAttributes]?: NField[K] } & { [K in keyof NField & keyof NFieldAttributes as `attr:${K}`]?: NFieldAttributes[K] } & { [K in keyof NField & keyof NFieldAttributes as `prop:${K}`]?: NField[K] };
        "n-input": Omit<NInput, keyof NInputAttributes> & { [K in keyof NInput & keyof NInputAttributes]?: NInput[K] } & { [K in keyof NInput & keyof NInputAttributes as `attr:${K}`]?: NInputAttributes[K] } & { [K in keyof NInput & keyof NInputAttributes as `prop:${K}`]?: NInput[K] };
        "n-loading": Omit<NLoading, keyof NLoadingAttributes> & { [K in keyof NLoading & keyof NLoadingAttributes]?: NLoading[K] } & { [K in keyof NLoading & keyof NLoadingAttributes as `attr:${K}`]?: NLoadingAttributes[K] } & { [K in keyof NLoading & keyof NLoadingAttributes as `prop:${K}`]?: NLoading[K] };
        "n-progress": Omit<NProgress, keyof NProgressAttributes> & { [K in keyof NProgress & keyof NProgressAttributes]?: NProgress[K] } & { [K in keyof NProgress & keyof NProgressAttributes as `attr:${K}`]?: NProgressAttributes[K] } & { [K in keyof NProgress & keyof NProgressAttributes as `prop:${K}`]?: NProgress[K] } & OneOf<"backgroundColorCode", NProgress["backgroundColorCode"], NProgressAttributes["backgroundColorCode"]>;
        "n-switch": Omit<NSwitch, keyof NSwitchAttributes> & { [K in keyof NSwitch & keyof NSwitchAttributes]?: NSwitch[K] } & { [K in keyof NSwitch & keyof NSwitchAttributes as `attr:${K}`]?: NSwitchAttributes[K] } & { [K in keyof NSwitch & keyof NSwitchAttributes as `prop:${K}`]?: NSwitch[K] };
        "n-table": Omit<NTable, keyof NTableAttributes> & { [K in keyof NTable & keyof NTableAttributes]?: NTable[K] } & { [K in keyof NTable & keyof NTableAttributes as `attr:${K}`]?: NTableAttributes[K] } & { [K in keyof NTable & keyof NTableAttributes as `prop:${K}`]?: NTable[K] };
        "n-table-column": Omit<NTableColumn, keyof NTableColumnAttributes> & { [K in keyof NTableColumn & keyof NTableColumnAttributes]?: NTableColumn[K] } & { [K in keyof NTableColumn & keyof NTableColumnAttributes as `attr:${K}`]?: NTableColumnAttributes[K] } & { [K in keyof NTableColumn & keyof NTableColumnAttributes as `prop:${K}`]?: NTableColumn[K] };
        "n-table-header": Omit<NTableHeader, keyof NTableHeaderAttributes> & { [K in keyof NTableHeader & keyof NTableHeaderAttributes]?: NTableHeader[K] } & { [K in keyof NTableHeader & keyof NTableHeaderAttributes as `attr:${K}`]?: NTableHeaderAttributes[K] } & { [K in keyof NTableHeader & keyof NTableHeaderAttributes as `prop:${K}`]?: NTableHeader[K] } & OneOf<"prop", NTableHeader["prop"], NTableHeaderAttributes["prop"]> & OneOf<"label", NTableHeader["label"], NTableHeaderAttributes["label"]>;
        "n-table-row": Omit<NTableRow, keyof NTableRowAttributes> & { [K in keyof NTableRow & keyof NTableRowAttributes]?: NTableRow[K] } & { [K in keyof NTableRow & keyof NTableRowAttributes as `attr:${K}`]?: NTableRowAttributes[K] } & { [K in keyof NTableRow & keyof NTableRowAttributes as `prop:${K}`]?: NTableRow[K] };
        "n-text": Omit<NText, keyof NTextAttributes> & { [K in keyof NText & keyof NTextAttributes]?: NText[K] } & { [K in keyof NText & keyof NTextAttributes as `attr:${K}`]?: NTextAttributes[K] } & { [K in keyof NText & keyof NTextAttributes as `prop:${K}`]?: NText[K] };
        "n-toast": Omit<NToast, keyof NToastAttributes> & { [K in keyof NToast & keyof NToastAttributes]?: NToast[K] } & { [K in keyof NToast & keyof NToastAttributes as `attr:${K}`]?: NToastAttributes[K] } & { [K in keyof NToast & keyof NToastAttributes as `prop:${K}`]?: NToast[K] };
        "n-toast-item": Omit<NToastItem, keyof NToastItemAttributes> & { [K in keyof NToastItem & keyof NToastItemAttributes]?: NToastItem[K] } & { [K in keyof NToastItem & keyof NToastItemAttributes as `attr:${K}`]?: NToastItemAttributes[K] } & { [K in keyof NToastItem & keyof NToastItemAttributes as `prop:${K}`]?: NToastItem[K] } & OneOf<"toastId", NToastItem["toastId"], NToastItemAttributes["toastId"]> & OneOf<"index", NToastItem["index"], NToastItemAttributes["index"]> & OneOf<"depth", NToastItem["depth"], NToastItemAttributes["depth"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "n-accordion": LocalJSX.IntrinsicElements["n-accordion"] & JSXBase.HTMLAttributes<HTMLNAccordionElement>;
            "n-accordion-group": LocalJSX.IntrinsicElements["n-accordion-group"] & JSXBase.HTMLAttributes<HTMLNAccordionGroupElement>;
            "n-bottom-sheet": LocalJSX.IntrinsicElements["n-bottom-sheet"] & JSXBase.HTMLAttributes<HTMLNBottomSheetElement>;
            "n-box": LocalJSX.IntrinsicElements["n-box"] & JSXBase.HTMLAttributes<HTMLNBoxElement>;
            "n-button": LocalJSX.IntrinsicElements["n-button"] & JSXBase.HTMLAttributes<HTMLNButtonElement>;
            "n-button-icon": LocalJSX.IntrinsicElements["n-button-icon"] & JSXBase.HTMLAttributes<HTMLNButtonIconElement>;
            "n-button-toggle": LocalJSX.IntrinsicElements["n-button-toggle"] & JSXBase.HTMLAttributes<HTMLNButtonToggleElement>;
            "n-button-toggle-group": LocalJSX.IntrinsicElements["n-button-toggle-group"] & JSXBase.HTMLAttributes<HTMLNButtonToggleGroupElement>;
            "n-cheap": LocalJSX.IntrinsicElements["n-cheap"] & JSXBase.HTMLAttributes<HTMLNCheapElement>;
            "n-dialog": LocalJSX.IntrinsicElements["n-dialog"] & JSXBase.HTMLAttributes<HTMLNDialogElement>;
            "n-dialog-item": LocalJSX.IntrinsicElements["n-dialog-item"] & JSXBase.HTMLAttributes<HTMLNDialogItemElement>;
            "n-drop": LocalJSX.IntrinsicElements["n-drop"] & JSXBase.HTMLAttributes<HTMLNDropElement>;
            "n-dynamic-component": LocalJSX.IntrinsicElements["n-dynamic-component"] & JSXBase.HTMLAttributes<HTMLNDynamicComponentElement>;
            "n-fade": LocalJSX.IntrinsicElements["n-fade"] & JSXBase.HTMLAttributes<HTMLNFadeElement>;
            "n-field": LocalJSX.IntrinsicElements["n-field"] & JSXBase.HTMLAttributes<HTMLNFieldElement>;
            "n-input": LocalJSX.IntrinsicElements["n-input"] & JSXBase.HTMLAttributes<HTMLNInputElement>;
            "n-loading": LocalJSX.IntrinsicElements["n-loading"] & JSXBase.HTMLAttributes<HTMLNLoadingElement>;
            "n-progress": LocalJSX.IntrinsicElements["n-progress"] & JSXBase.HTMLAttributes<HTMLNProgressElement>;
            "n-switch": LocalJSX.IntrinsicElements["n-switch"] & JSXBase.HTMLAttributes<HTMLNSwitchElement>;
            "n-table": LocalJSX.IntrinsicElements["n-table"] & JSXBase.HTMLAttributes<HTMLNTableElement>;
            "n-table-column": LocalJSX.IntrinsicElements["n-table-column"] & JSXBase.HTMLAttributes<HTMLNTableColumnElement>;
            "n-table-header": LocalJSX.IntrinsicElements["n-table-header"] & JSXBase.HTMLAttributes<HTMLNTableHeaderElement>;
            "n-table-row": LocalJSX.IntrinsicElements["n-table-row"] & JSXBase.HTMLAttributes<HTMLNTableRowElement>;
            "n-text": LocalJSX.IntrinsicElements["n-text"] & JSXBase.HTMLAttributes<HTMLNTextElement>;
            "n-toast": LocalJSX.IntrinsicElements["n-toast"] & JSXBase.HTMLAttributes<HTMLNToastElement>;
            "n-toast-item": LocalJSX.IntrinsicElements["n-toast-item"] & JSXBase.HTMLAttributes<HTMLNToastItemElement>;
        }
    }
}
